"use client";

import { useState, useTransition } from "react";
import { savePolicy } from "@/app/actions/admin";
import type { AdminPolicy } from "@/lib/admin-operations";

export function AdminPolicyForm({ policy }: { policy: AdminPolicy }) {
  const [body, setBody] = useState(policy.body); const [version, setVersion] = useState(policy.version); const [active, setActive] = useState(policy.is_active); const [message, setMessage] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  return <form className="pi-admin-form" onSubmit={(event) => { event.preventDefault(); setMessage(null); startTransition(async () => { const result = await savePolicy({ id: policy.id, body, version, active }); setMessage(result.ok ? "Policy saved." : result.error); }); }}>
    <label>Version<input required maxLength={80} value={version} onChange={(event) => setVersion(event.target.value)} /></label><label>Approved legal text<textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Paste approved legal copy here. No wording is generated by this dashboard." /></label><label className="pi-admin-check"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} /> Active</label>{message ? <p className={message === "Policy saved." ? "pi-admin-success" : "pi-admin-error"}>{message}</p> : null}<button className="pi-admin-button" disabled={pending} type="submit">{pending ? "Saving…" : "Save policy"}</button>
  </form>;
}
