import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { Container } from "@/components/Container";
import { Section } from "@/components/Section";
import { Eyebrow } from "@/components/Eyebrow";
import { ButtonLink } from "@/components/Button";
import { CatalogDocumentCard } from "@/components/CatalogDocumentCard";
import { GalleryLightbox } from "@/components/GalleryLightbox";
import { MediaBlock } from "@/components/MediaBlock";
import { SOCOTRA_DAYS, SOCOTRA_GALLERY } from "@/content/socotra";
export const metadata: Metadata = { title:"Socotra", description:"An eight-day Socotra camping journey with Planet Infinity. Request your place from Jeddah, with no payment at the request stage.",alternates:{canonical:"/trips/socotra"},openGraph:{title:"Socotra — Planet Infinity",images:[{url:"/socotra/white-dunes-and-sea.jpeg",alt:"Socotra white dunes and turquoise sea"}]} };
export default function SocotraPage() {
 return <>
  <section className="pi-trip-cinema"><MediaBlock src="/socotra/white-dunes-and-sea.jpeg" alt="White dunes and the sea in Socotra, image supplied for this trip" ratio="21-9" radius="none" className="pi-trip-cinema__media" eager><Container className="pi-trip-cinema__content"><Breadcrumbs trail={[{label:"Home",href:"/"},{label:"Travel",href:"/trips"},{label:"Socotra"}]} /><Eyebrow>Socotra, Yemen</Eyebrow><h1>Socotra</h1><p>Eight days of white dunes, turquoise water and dragon blood forests. Meet the group in Jeddah and fly together to the island.</p><ButtonLink href="/trips/socotra/book">Request Booking</ButtonLink></Container></MediaBlock></section>
  <Section tone="white" className="pi-trip-document-rail"><Container><CatalogDocumentCard url="/documents/Socotra%20Trip%20Program.pdf" label="Socotra Trip Program · 8 days" kind="trip" /></Container></Section>
  <Section tone="white" className="pi-trip-story"><Container><div className="pi-trip-layout"><div className="pi-trip-main">
  <section className="pi-trip-block pi-trip-block--intro"><Eyebrow>Trip story</Eyebrow><h2>Overview</h2><p>Start at Detwah Lagoon, take a boat to Shuab Beach, and camp among the dragon blood trees of Firmhin. Continue through caves, dunes and natural pools to the coast at Arher, Dihamri and Delisha.</p></section>
  <section className="pi-trip-block pi-trip-block--gallery"><div className="pi-trip-block__head"><div><Eyebrow>The island, up close</Eyebrow><h2>Explore Socotra</h2></div><p>Tap a photo to open it.</p></div><GalleryLightbox images={SOCOTRA_GALLERY} layout="grid" /><p className="pi-booking__note">Kalisan Canyon photograph: Kristina Makeeva, as credited in the supplied file.</p></section>
  <section className="pi-trip-block"><Eyebrow>At a glance</Eyebrow><h2>Trip details</h2><dl className="pi-trip-facts">{[["Destination","Socotra, Yemen"],["Duration","8 days / 7 nights"],["Meet the group","Jeddah, Saudi Arabia"],["Included flights","From Jeddah to Socotra, then back to Jeddah"],["Accommodation","Camping, following the supplied program"],["Departures","26 Nov–3 Dec 2026 · 7–14 Jan 2027 · 11–18 Mar 2027 (proposed)"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
  <section className="pi-trip-block"><h2>What is included</h2><div className="pi-includes"><ul className="pi-includes__list pi-includes__list--in">{["Your flight from Jeddah to Socotra and back, according to the confirmed package","Socotra entry visa, subject to eligibility and approval","4×4 transport and an English-speaking guide","Camping equipment, campsite fees and a cook","Three meals daily with drinks","The boat trip in the program"].map(item=><li key={item}>{item}</li>)}</ul><div><h3 className="pi-includes__subtitle">Not included</h3><ul className="pi-includes__list pi-includes__list--out"><li>Travel from your home country to Jeddah and back</li><li>Personal expenses and tips</li></ul><p>Saudi entry/transit, insurance and snorkeling or diving rental costs require separate review.</p></div></div></section>
  <section className="pi-trip-block"><h2>Itinerary</h2><ol className="pi-itinerary">{SOCOTRA_DAYS.map(([title,body],index)=><li key={title}><p className="pi-itinerary__label">Day {index+1}</p><h3 className="pi-itinerary__title">{title}</h3><p className="pi-itinerary__body">{body}</p></li>)}</ol></section>
  <section className="pi-trip-block"><h2>Important information</h2><ul className="pi-notes"><li>Dates are proposed. Flight schedule, availability and visa eligibility are confirmed individually before a booking is accepted.</li><li>The package starts and ends in Jeddah. Connections from other countries are quoted separately.</li><li>The operator PDF excludes flights; Planet Infinity adds return Jeddah–Socotra flights to this package. Its Tuesday flight note must be reconciled with the proposed Thursday departures.</li><li>Wildlife sightings and water activities depend on conditions.</li><li>The museum visit is included in the operator PDF; its timing requires confirmation.</li><li>Review travel advice from your country and check insurance cover. The UK FCDO advises against all travel to Yemen; <a href="https://www.gov.uk/foreign-travel-advice/yemen" target="_blank" rel="noreferrer">read current advice</a>.</li></ul></section>
  </div><aside className="pi-trip-aside" aria-label="Booking options"><div className="pi-booking"><div className="pi-booking__head"><div className="pi-price pi-price--large">$2,190 <span className="pi-price__unit">USD per traveler · Early Bird</span></div></div><p className="pi-booking__note">Regular price: $2,290 USD. Your applicable offer is confirmed by our team.</p><div className="pi-booking__overview"><span>Your island journey</span><p>8 days / 7 nights. Meet the group in Jeddah; the flight to Socotra and back is included.</p></div><ol className="pi-booking__steps">{["Your choices","Trip questions","Your details","Review"].map((label,i)=><li key={label}><span className="pi-booking__step-num">{i+1}</span>{label}</li>)}</ol><ButtonLink href="/trips/socotra/book" className="pi-booking__cta">Request Booking</ButtonLink><p className="pi-booking__note">A request is reviewed before confirmation. No payment is collected.</p></div></aside>
  </div></Container></Section>
 </>;
}
