export const SITE_COPY_FIELDS = [
  { key: "home_eyebrow", label: "Home eyebrow", fallback: "Planet Infinity", multiline: false },
  { key: "home_title", label: "Home headline", fallback: "Your next world starts here.", multiline: false },
  { key: "home_lede", label: "Home introduction", fallback: "Discover trips, experiences and events made to feel like their own world.", multiline: true },
  { key: "home_trips_cta", label: "Home trips button", fallback: "Explore trips", multiline: false },
  { key: "home_events_cta", label: "Home events button", fallback: "Explore events", multiline: false },
  { key: "home_feature_label", label: "Featured trip label", fallback: "Featured trip", multiline: false },
  { key: "home_feature_cta", label: "Featured trip link", fallback: "View trip details", multiline: false },
  { key: "home_trips_title", label: "Home trips heading", fallback: "Trips you can join", multiline: false },
  { key: "home_trips_lede", label: "Home trips introduction", fallback: "Real departures, clear details and a booking path that matches each trip.", multiline: true },
  { key: "home_trips_all", label: "Home all trips link", fallback: "View all trips", multiline: false },
  { key: "home_trips_empty_title", label: "Home empty trips heading", fallback: "The next trip is taking shape", multiline: false },
  { key: "home_trips_empty_body", label: "Home empty trips text", fallback: "New departures will appear here as soon as they are published.", multiline: true },
  { key: "home_events_title", label: "Home events heading", fallback: "Events worth showing up for", multiline: false },
  { key: "home_events_lede", label: "Home events introduction", fallback: "Daytime gatherings, creative sessions and nights with their own energy.", multiline: true },
  { key: "home_events_all", label: "Home all events link", fallback: "Enter the events world", multiline: false },
  { key: "home_events_empty_title", label: "Home empty events heading", fallback: "The next event is taking shape", multiline: false },
  { key: "home_events_empty_body", label: "Home empty events text", fallback: "It will appear here as soon as the date and ticket details are certain.", multiline: true },
  { key: "trips_title", label: "Trips page headline", fallback: "Every trip we run", multiline: false },
  { key: "trips_lede", label: "Trips page introduction", fallback: "Desert and sea, camping and stargazing, long roads and short escapes — planned and run by Planet Infinity.", multiline: true },
  { key: "trips_empty_title", label: "Trips empty heading", fallback: "The trip line-up is being finalised", multiline: false },
  { key: "trips_empty_body", label: "Trips empty text", fallback: "Departures, prices and meeting points are confirmed before anything is listed.", multiline: true },
  { key: "events_title", label: "Events page headline", fallback: "Events with a world of their own", multiline: false },
  { key: "events_lede", label: "Events page introduction", fallback: "From daytime gatherings to after-dark experiences, every event is announced only when its details are ready.", multiline: true },
  { key: "events_empty_title", label: "Events empty heading", fallback: "The next dates are being locked in", multiline: false },
  { key: "events_empty_body", label: "Events empty text", fallback: "Line-ups, venues and ticket details are confirmed before an event is listed.", multiline: true },
  { key: "themes_eyebrow", label: "Themes page eyebrow", fallback: "Story worlds", multiline: false },
  { key: "themes_title", label: "Themes page headline", fallback: "Enter a world. Make it yours.", multiline: false },
  { key: "themes_lede", label: "Themes page introduction", fallback: "Immersive Planet Infinity stories that can become a trip, an event, or a custom experience.", multiline: true },
  { key: "themes_empty_title", label: "Themes empty heading", fallback: "The next world is being built", multiline: false },
  { key: "themes_empty_body", label: "Themes empty text", fallback: "New themed experiences will appear here when their story and details are ready.", multiline: true },
  { key: "explore_title", label: "Explore page headline", fallback: "One planet. More than one world.", multiline: false },
  { key: "explore_lede", label: "Explore page introduction", fallback: "Move between travel and events as the Planet Infinity universe changes around you.", multiline: true },
  { key: "trip_overview_title", label: "Trip overview heading", fallback: "Overview", multiline: false },
  { key: "trip_gallery_title", label: "Trip gallery heading", fallback: "Gallery", multiline: false },
  { key: "trip_gallery_hint", label: "Trip gallery instruction", fallback: "Tap any image to open it.", multiline: false },
  { key: "trip_details_title", label: "Trip details heading", fallback: "Trip details", multiline: false },
  { key: "trip_document_title", label: "Trip document heading", fallback: "Trip document", multiline: false },
  { key: "trip_included_title", label: "Trip included heading", fallback: "What is included", multiline: false },
  { key: "trip_not_included_title", label: "Trip not included heading", fallback: "Not included", multiline: false },
  { key: "trip_itinerary_title", label: "Trip itinerary heading", fallback: "Itinerary", multiline: false },
  { key: "trip_information_title", label: "Trip information heading", fallback: "Important information", multiline: false },
  { key: "trip_questions_title", label: "Trip questions heading", fallback: "Questions", multiline: false },
  { key: "trip_cancellation_title", label: "Trip cancellation heading", fallback: "Cancellation", multiline: false },
  { key: "event_overview_title", label: "Event overview heading", fallback: "About the event", multiline: false },
  { key: "event_gallery_title", label: "Event gallery heading", fallback: "Gallery", multiline: false },
  { key: "event_document_title", label: "Event document heading", fallback: "Event document", multiline: false },
  { key: "event_information_title", label: "Event information heading", fallback: "Important information", multiline: false },
  { key: "event_questions_title", label: "Event questions heading", fallback: "Questions", multiline: false },
  { key: "event_cancellation_title", label: "Event cancellation heading", fallback: "Cancellation", multiline: false },
  { key: "footer_tagline", label: "Footer tagline", fallback: "Entertainment, community and experiences.\nOne brand, more than one world.", multiline: true },
  { key: "contact_title", label: "Contact page headline", fallback: "Talk to us", multiline: false },
  { key: "contact_lede", label: "Contact page introduction", fallback: "The person who answers is the person who will be there on the day.", multiline: true },
  { key: "contact_whatsapp", label: "Contact WhatsApp", fallback: "+20 103 729 9464", multiline: false },
  { key: "contact_email", label: "Contact email", fallback: "planetinfinity2023@gmail.com", multiline: false },
  { key: "contact_address", label: "Business address", fallback: "45 Sheikh Mohamed El Ghazali Street, Dokki, Giza, Egypt", multiline: true },
  { key: "contact_office_hours", label: "Office hours", fallback: "", multiline: false },
  { key: "contact_emergency", label: "Emergency contact", fallback: "", multiline: false },
  { key: "careers_eyebrow", label: "Careers header eyebrow", fallback: "Planet Infinity · Careers", multiline: false },
  { key: "careers_title", label: "Careers page headline", fallback: "Join the story", multiline: false },
  { key: "careers_subtitle", label: "Careers header subheadline", fallback: "We're looking for characters, not employees.", multiline: false },
  { key: "careers_lede", label: "Careers header introduction", fallback: "We don't hire CVs. We hire people — the ones with a bit of soul, who make a bus of strangers feel like a family by hour two. Tell us who you are, what you're good at, and how you move through the world. Experience helps. Personality decides.", multiline: true },
  { key: "careers_roles_question", label: "Careers roles question", fallback: "Which role are you applying for?", multiline: false },
  { key: "careers_roles_options", label: "Careers role choices — one per line", fallback: "Content Creator\nVideographer\nTravel Consultant\nSales\nTrip Counselor\nExperience Crew\nOperations", multiline: true },
  { key: "careers_music_question", label: "Careers music question", fallback: "Your music taste (this matters more than you think)", multiline: false },
  { key: "careers_music_options", label: "Careers music choices — one per line", fallback: "Pop / Hits\nArabic / Shaabi\nTechno / House\nR&B / Chill\nRock\nAnything, I'm easy", multiline: true },
] as const;

export type SiteCopyKey = (typeof SITE_COPY_FIELDS)[number]["key"];
export type SiteCopy = Record<SiteCopyKey, string>;

export const SITE_COPY_DEFAULTS = Object.fromEntries(
  SITE_COPY_FIELDS.map((field) => [field.key, field.fallback]),
) as SiteCopy;
